### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yuki526** [yuki526/protospace-32050#1]
よろしくお願いいたします。
URL
https://protospace-32050.herokuapp.com/

**Comment by junkiyamada** [comment]
上山様、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by yuki526** [comment]
ご確認いただきありがとうございました！
今後ともよろしくお願いいたします。
